### ISSUE TITLE
Version file

### ISSUE THREAD

**Issue by Bear67** [JPLRepo/KabinKraziness#1]
Kabin Kraziness.version file is pointed at AmpYear's version file (web page). so It's giving wrong version in the KSP-AVC module.

**Comment by JPLRepo** [comment]
Hmmm. Shouldn't give wrong version.
But the link is the wrong one. I'll fix it next version.

**Comment by Bear67** [comment]
I finally got around to taking a screen shot.
![screenshot_2](https://cloud.githubusercontent.com/assets/5138687/17455841/25c8daa0-5b8a-11e6-85ac-d4537b0a2331.jpg)
When I chose Actions-Download it loads the AmpYear page.

**Comment by JPLRepo** [comment]
This should be fixed.
